### ISSUE TITLE
[人事労務] 「勤怠の操作」で例示されているパラメータが正しくない

### ISSUE THREAD

**Issue by mkht** [freee/freee-api-schema#188]
人事労務APIレファレンスの[勤怠情報更新操作の項](https://developer.freee.co.jp/reference/hr/reference#/%E5%8B%A4%E6%80%A0/update_employee_work_record)にてexamplesに例示されている
リクエストパラメータが正しくないため、例の通りのパラメータでリクエストを行うと`400 Bad Request`が返ってきます。

### レファレンスで例示されているパラメータ
<img width="742" alt="image" src="https://user-images.githubusercontent.com/25482642/182419624-fdd49e1a-0a35-42a9-893f-38d1392a0e89.png">

### 正しいパラメータ
```json
{
  "company_id": 1,
  "break_records": [
    {
      "clock_in_at": "2017-05-25 12:00:00",
      "clock_out_at": "2017-05-25 13:00:00"
    }
  ],
  "clock_in_at": "2017-05-25 09:10:00",
  "clock_out_at": "2017-05-25 18:20:00"
}
```

修正頂ければ幸いです。

**Comment by sakakibara-setu** [comment]
@mkht 
ご指摘ありがとうございます。
混乱を招いてしまい、申し訳ございません。近日中に修正作業を行います。
よろしくお願いいたします。

**Comment by sakakibara-setu** [comment]
こちら対応が完了したため、closeします
