### ISSUE TITLE
manual_journalsの中のsegment_1_tag_name,segment_2_tag_name,segment_3_tag_nameの型が、stringであるべきところがintegerになっています。

### ISSUE THREAD

**Issue by taskooh** [freee/freee-api-schema#201]
https://github.com/freee/freee-api-schema/blob/91d086232aa56fcc9168a93d5746743e613aa13e/_sdk_compatible/open-api-3/api-schema.yml#L17805

こちらのyamlを元に生成したgoのsdkを用いてダウンロードしてJSONの型変換を行ったところ、該当箇所でエラーが発生しました。

ご確認をお願いします。

**Comment by sakakibara-setu** [comment]
@taskooh 
ご指摘ありがとうございます。
混乱を招いてしまい、申し訳ございません。確認致します。

**Comment by sakakibara-setu** [comment]
こちら修正済みのためcloseします
